/* ==================================================================
   Step 7: Fraud vs legit feature separation
   PURPOSE: Compare FRAUD vs LEGIT averages per feature to gauge separation
   DETAILS:
     RPT_FEATURE_AVERAGES: per-split (TRAIN/TEST) averages and differences
     Features: V1-V28 plus AMOUNT
     Includes DIFF = FRAUD_AVG - LEGIT_AVG
              SEPARATION = absolute value of DIFF
   ================================================================== */

USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DETECTION;
USE SCHEMA REPORTING;

-- Per-split fraud/legit averages, then unpivot via UNION ALL
CREATE OR REPLACE VIEW RPT_FEATURE_AVERAGES
COMMENT = 'Fraud vs legit feature averages with DIFF and SEPARATION per split' AS
WITH FRAUD_STATS AS (
    SELECT
        SPLIT,
        AVG(IFF(IS_FRAUD, V1 , NULL)) AS FRAUD_V1 ,  AVG(IFF(NOT IS_FRAUD, V1 , NULL)) AS LEGIT_V1,
        AVG(IFF(IS_FRAUD, V2 , NULL)) AS FRAUD_V2 ,  AVG(IFF(NOT IS_FRAUD, V2 , NULL)) AS LEGIT_V2,
        AVG(IFF(IS_FRAUD, V3 , NULL)) AS FRAUD_V3 ,  AVG(IFF(NOT IS_FRAUD, V3 , NULL)) AS LEGIT_V3,
        AVG(IFF(IS_FRAUD, V4 , NULL)) AS FRAUD_V4 ,  AVG(IFF(NOT IS_FRAUD, V4 , NULL)) AS LEGIT_V4,
        AVG(IFF(IS_FRAUD, V5 , NULL)) AS FRAUD_V5 ,  AVG(IFF(NOT IS_FRAUD, V5 , NULL)) AS LEGIT_V5,
        AVG(IFF(IS_FRAUD, V6 , NULL)) AS FRAUD_V6 ,  AVG(IFF(NOT IS_FRAUD, V6 , NULL)) AS LEGIT_V6,
        AVG(IFF(IS_FRAUD, V7 , NULL)) AS FRAUD_V7 ,  AVG(IFF(NOT IS_FRAUD, V7 , NULL)) AS LEGIT_V7,
        AVG(IFF(IS_FRAUD, V8 , NULL)) AS FRAUD_V8 ,  AVG(IFF(NOT IS_FRAUD, V8 , NULL)) AS LEGIT_V8,
        AVG(IFF(IS_FRAUD, V9 , NULL)) AS FRAUD_V9 ,  AVG(IFF(NOT IS_FRAUD, V9 , NULL)) AS LEGIT_V9,
        AVG(IFF(IS_FRAUD, V10, NULL)) AS FRAUD_V10,  AVG(IFF(NOT IS_FRAUD, V10, NULL)) AS LEGIT_V10,
        AVG(IFF(IS_FRAUD, V11, NULL)) AS FRAUD_V11,  AVG(IFF(NOT IS_FRAUD, V11, NULL)) AS LEGIT_V11,
        AVG(IFF(IS_FRAUD, V12, NULL)) AS FRAUD_V12,  AVG(IFF(NOT IS_FRAUD, V12, NULL)) AS LEGIT_V12,
        AVG(IFF(IS_FRAUD, V13, NULL)) AS FRAUD_V13,  AVG(IFF(NOT IS_FRAUD, V13, NULL)) AS LEGIT_V13,
        AVG(IFF(IS_FRAUD, V14, NULL)) AS FRAUD_V14,  AVG(IFF(NOT IS_FRAUD, V14, NULL)) AS LEGIT_V14,
        AVG(IFF(IS_FRAUD, V15, NULL)) AS FRAUD_V15,  AVG(IFF(NOT IS_FRAUD, V15, NULL)) AS LEGIT_V15,
        AVG(IFF(IS_FRAUD, V16, NULL)) AS FRAUD_V16,  AVG(IFF(NOT IS_FRAUD, V16, NULL)) AS LEGIT_V16,
        AVG(IFF(IS_FRAUD, V17, NULL)) AS FRAUD_V17,  AVG(IFF(NOT IS_FRAUD, V17, NULL)) AS LEGIT_V17,
        AVG(IFF(IS_FRAUD, V18, NULL)) AS FRAUD_V18,  AVG(IFF(NOT IS_FRAUD, V18, NULL)) AS LEGIT_V18,
        AVG(IFF(IS_FRAUD, V19, NULL)) AS FRAUD_V19,  AVG(IFF(NOT IS_FRAUD, V19, NULL)) AS LEGIT_V19,
        AVG(IFF(IS_FRAUD, V20, NULL)) AS FRAUD_V20,  AVG(IFF(NOT IS_FRAUD, V20, NULL)) AS LEGIT_V20,
        AVG(IFF(IS_FRAUD, V21, NULL)) AS FRAUD_V21,  AVG(IFF(NOT IS_FRAUD, V21, NULL)) AS LEGIT_V21,
        AVG(IFF(IS_FRAUD, V22, NULL)) AS FRAUD_V22,  AVG(IFF(NOT IS_FRAUD, V22, NULL)) AS LEGIT_V22,
        AVG(IFF(IS_FRAUD, V23, NULL)) AS FRAUD_V23,  AVG(IFF(NOT IS_FRAUD, V23, NULL)) AS LEGIT_V23,
        AVG(IFF(IS_FRAUD, V24, NULL)) AS FRAUD_V24,  AVG(IFF(NOT IS_FRAUD, V24, NULL)) AS LEGIT_V24,
        AVG(IFF(IS_FRAUD, V25, NULL)) AS FRAUD_V25,  AVG(IFF(NOT IS_FRAUD, V25, NULL)) AS LEGIT_V25,
        AVG(IFF(IS_FRAUD, V26, NULL)) AS FRAUD_V26,  AVG(IFF(NOT IS_FRAUD, V26, NULL)) AS LEGIT_V26,
        AVG(IFF(IS_FRAUD, V27, NULL)) AS FRAUD_V27,  AVG(IFF(NOT IS_FRAUD, V27, NULL)) AS LEGIT_V27,
        AVG(IFF(IS_FRAUD, V28, NULL)) AS FRAUD_V28,  AVG(IFF(NOT IS_FRAUD, V28, NULL)) AS LEGIT_V28,
        AVG(IFF(IS_FRAUD, AMOUNT, NULL))     AS FRAUD_AMOUNT,
        AVG(IFF(NOT IS_FRAUD, AMOUNT, NULL)) AS LEGIT_AMOUNT
    FROM FRAUD_DETECTION.ANALYTICS.TRANSACTIONS_SPLIT
    WHERE SPLIT IN ('TRAIN', 'TEST')  -- exclude VALID: reserve for model selection
    GROUP BY SPLIT
)
SELECT
    SPLIT,
    FEATURE,
    FRAUD_AVG,
    LEGIT_AVG,
    (FRAUD_AVG - LEGIT_AVG) AS DIFF,
    ABS(FRAUD_AVG - LEGIT_AVG) AS SEPARATION  -- absolute value of difference
FROM (
    SELECT SPLIT, 'V1' AS FEATURE,      FRAUD_V1 AS FRAUD_AVG, LEGIT_V1 AS LEGIT_AVG FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V2'                , FRAUD_V2  , LEGIT_V2   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V3'                , FRAUD_V3  , LEGIT_V3   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V4'                , FRAUD_V4  , LEGIT_V4   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V5'                , FRAUD_V5  , LEGIT_V5   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V6'                , FRAUD_V6  , LEGIT_V6   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V7'                , FRAUD_V7  , LEGIT_V7   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V8'                , FRAUD_V8  , LEGIT_V8   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V9'                , FRAUD_V9  , LEGIT_V9   FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V10'               , FRAUD_V10 , LEGIT_V10  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V11'               , FRAUD_V11 , LEGIT_V11  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V12'               , FRAUD_V12 , LEGIT_V12  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V13'               , FRAUD_V13 , LEGIT_V13  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V14'               , FRAUD_V14 , LEGIT_V14  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V15'               , FRAUD_V15 , LEGIT_V15  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V16'               , FRAUD_V16 , LEGIT_V16  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V17'               , FRAUD_V17 , LEGIT_V17  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V18'               , FRAUD_V18 , LEGIT_V18  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V19'               , FRAUD_V19 , LEGIT_V19  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V20'               , FRAUD_V20 , LEGIT_V20  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V21'               , FRAUD_V21 , LEGIT_V21  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V22'               , FRAUD_V22 , LEGIT_V22  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V23'               , FRAUD_V23 , LEGIT_V23  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V24'               , FRAUD_V24 , LEGIT_V24  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V25'               , FRAUD_V25 , LEGIT_V25  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V26'               , FRAUD_V26 , LEGIT_V26  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V27'               , FRAUD_V27 , LEGIT_V27  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'V28'               , FRAUD_V28 , LEGIT_V28  FROM FRAUD_STATS UNION ALL
    SELECT SPLIT, 'AMOUNT',             FRAUD_AMOUNT, LEGIT_AMOUNT FROM FRAUD_STATS    
) T;

-- SELECT * FROM RPT_FEATURE_AVERAGES ORDER BY SPLIT, SEPARATION DESC;