/* ==================================================================
   Step 11: Export reporting views to CSV
   PURPOSE: Produce reproducible CSV extracts for Tableau
   DETAILS:
     Target stage: REPORTING.EXPORT_STAGE
     Settings: HEADER=TRUE, SINGLE=TRUE, OVERWRITE=TRUE, COMPRESSION=NONE
   ================================================================== */

USE WAREHOUSE FRAUD_WH;
USE DATABASE FRAUD_DETECTION;
USE SCHEMA REPORTING;

CREATE OR REPLACE STAGE EXPORT_STAGE;

-- Header KPIs
COPY INTO @EXPORT_STAGE/RPT_DASHBOARD_HEADER/
FROM (
    SELECT * FROM RPT_DASHBOARD_HEADER
    ORDER BY SPLIT
)
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Feature separation
COPY INTO @EXPORT_STAGE/RPT_FEATURE_SEPARATION_SUMMARY/
FROM (
    SELECT * FROM RPT_FEATURE_SEPARATION_SUMMARY
    WHERE SPLIT = 'TEST'
    ORDER BY SEPARATION DESC, FEATURE
)
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Histogram statistics
COPY INTO @EXPORT_STAGE/RPT_FEATURE_PROFILE/
FROM (
    SELECT * FROM RPT_FEATURE_PROFILE
    ORDER BY SPLIT, FEATURE_RANK
)
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Histogram bins
COPY INTO @EXPORT_STAGE/RPT_FEATURE_DRILL_DOWN_BINS/
FROM (
    SELECT * FROM RPT_FEATURE_DRILL_DOWN_BINS
    ORDER BY SPLIT, FEATURE, BIN
)
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Scatter pairs
COPY INTO @EXPORT_STAGE/RPT_SCATTER_FEATURE_PAIRS/
FROM (
    SELECT * FROM RPT_SCATTER_FEATURE_PAIRS
    ORDER BY pair_name, CLASS_LABEL
)
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Confirm files exist
LIST @EXPORT_STAGE;

-- Optional cleanup between runs (uncomment to clear a folder before re-exporting)
-- REMOVE @EXPORT_STAGE/RPT_DASHBOARD_HEADER/;
-- REMOVE @EXPORT_STAGE/RPT_FEATURE_SEPARATION_SUMMARY/;
-- REMOVE @EXPORT_STAGE/RPT_FEATURE_PROFILE/;
-- REMOVE @EXPORT_STAGE/RPT_FEATURE_DRILL_DOWN_BINS/;
-- REMOVE @EXPORT_STAGE/RPT_SCATTER_FEATURE_PAIRS/;